[package]
name = "png2mozjpegd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.24.6", default-features = false, features = [ "png" ] }
mozjpeg = "0.9.6"
notify = "6.0.0"
tokio = { version = "1.28.2", features = ["rt-multi-thread", "time", "macros"] , default-features = false}
serde = { version = "1.0.164" , features = ["derive"] }
serde_yaml = "0.9.21"
once_cell = "1.18.0"
walkdir = "2.3.3"
dirs = "5.0.1"
num_cpus = "1.16.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
